---
 - name: Apt update
   apt: update_cache=yes

 - name: install libssl-dev
   apt: name={{ item }} state=present
   with_items:
     - build-essential
     - git
     - curl
     - wget
     - libcurl4-openssl-dev
     - libffi-dev
     - libreadline-dev
     - libssl-dev
     - libxml2-dev
     - libxslt1-dev
     - zlib1g-dev

 - name: Clone rbenv git repository
   git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv

 - name: Configuration Env 
   copy: src=rbenv.sh dest=/etc/profile.d/rbenv.sh

 - name: Configuration Env 
   shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
 
 - name: Configuration Env 
   shell: echo 'eval "$(rbenv init -)"' >> ~/.bashrc

 - name: Clone ruby-build
   git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

 - name: Install rbenv
   shell: bash -lc "rbenv install 2.2.1 && rbenv global 2.2.1 && rbenv rehash && gem update && gem install bundler"
